### ISSUE TITLE
Cluster with only itself.

### ISSUE THREAD

**Issue by hvdkooij** [ebesson/ansible-role-k3s#17]
I used the playbook with an inventory of:
'''
[k3s-master]
node1

[k3s-agent]
node2
node3'''

And I see node1 become the master. But node2 and node3 aren't doing anything it seems.

Any suggestions on how to troubleshoot?

**Comment by hvdkooij** [comment]
Can I adjust the playbook to deinstall nodes?

**Comment by ebesson** [comment]
> I used the playbook with an inventory of:
> '''
> [k3s-master]
> node1
> 
> [k3s-agent]
> node2
> node3'''
> 
> And I see node1 become the master. But node2 and node3 aren't doing anything it seems.
> 
> Any suggestions on how to troubleshoot?

**Comment by ebesson** [comment]
By default a node is _master_, this configuration is done with parameter `k3s_type: master` => on your node2 and node3, in order to define these nodes as _agent_, you must set this parameter:  `k3s_type: agent`, y

Here's as sample playbook : 
```yaml
---
- hosts: all
  vars:
    k3s_master_node_address: "{{ hostvars['master'].ansible_default_ipv4.address }}"
    k3s_cluster_token: "{{ hostvars['master']['k3s_cluster_token'] }}"

- hosts: k3s-master
  become: True
  vars:
    k3s_type: master
  roles:
    - ebesson.k3s

- hosts: k3s-agent
  become: True
  vars:
    k3s_type: agent
  roles:
    - ebesson.k3s
```

I've published an full example with vagrant : https://github.com/ebesson/ansible-k3s-playbook/
